# Generated by Django 5.1.7 on 2025-03-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstruction',
            name='product',
        ),
        migrations.AddField(
            model_name='productinstruction',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeshop.product'),
        ),
    ]
