# Generated by Django 5.1.7 on 2025-04-09 10:42

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0003_alter_cartitem_quantity_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='region', max_length=128, region='IN'),
        ),
    ]
