# Generated by Django 5.1.7 on 2025-04-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0004_useraddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='landmark',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='locality',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(default='User"s name', max_length=25),
        ),
    ]
