# Generated by Django 5.1.7 on 2025-04-15 05:58

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0005_useraddress_landmark_useraddress_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='alternate_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='region', max_length=128, region='IN'),
        ),
    ]
