# Generated by Django 5.2 on 2025-04-25 17:10

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0006_useraddress_alternate_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allabout', models.TextField()),
                ('centre1info', models.TextField()),
                ('centre2info', models.TextField()),
                ('centre3info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Footerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_About', models.CharField(max_length=265)),
                ('City', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='region', max_length=128, region='IN')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(default='region', max_length=128, region='IN')),
            ],
        ),
    ]
