# Generated by Django 5.2 on 2025-04-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0007_about_footerinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name_plural': 'Footer Informations'},
        ),
        migrations.AddField(
            model_name='about',
            name='centre1city',
            field=models.CharField(default='Mumbai', max_length=40),
        ),
        migrations.AddField(
            model_name='about',
            name='centre2city',
            field=models.CharField(default='Kolakata', max_length=40),
        ),
        migrations.AddField(
            model_name='about',
            name='centre3city',
            field=models.CharField(default='Banglore', max_length=40),
        ),
    ]
