# Generated by Django 5.2 on 2025-04-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0008_alter_about_options_alter_footerinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='centre1image',
            field=models.ImageField(null=True, upload_to='images/centre1'),
        ),
        migrations.AddField(
            model_name='about',
            name='centre2image',
            field=models.ImageField(null=True, upload_to='images/centre2'),
        ),
        migrations.AddField(
            model_name='about',
            name='centre3image',
            field=models.ImageField(null=True, upload_to='images/centre3'),
        ),
    ]
