# Generated by Django 5.2 on 2025-04-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0010_about_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mainimage',
            field=models.ImageField(null=True, upload_to='images/maincentre'),
        ),
    ]
