# Generated by Django 5.2 on 2025-05-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0013_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
