# Generated by Django 5.2 on 2025-05-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0014_rename_image_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(default='images/products/default image.jpg', upload_to='images/products'),
        ),
    ]
