# Generated by Django 5.2 on 2025-05-05 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0016_searchedquery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchedquery',
            options={'verbose_name': 'Searched Query', 'verbose_name_plural': 'Searched Queries'},
        ),
        migrations.AlterField(
            model_name='searchedquery',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
